graph TD
    A[password_cli Main App] --> B(password_core);
    A --> C{std::io};
    A --> D{termcolor};
    A --> E{rpassword};
    A --> F{serde_json};
    A --> G{zeroize};
    A --> H{env_logger};

    B --> B1(crypto);
    B --> B2(data_types);
    B --> B3(settings_manager);
    B --> B4(PasswordManagerError);

    subgraph Internal CLI Functions
        Z1(main);
        Z2(handle_user_login);
        Z3(print_vault_contents);
        Z4(get_password_input);
        Z5(pc);
    end

    A --- Z1;
    Z1 --> Z2;
    Z1 --> Z5;
    Z1 --> Z3;
    Z1 --> B3;
    Z1 --> H;

    Z2 --> Z5;
    Z2 --> Z4;
    Z2 --> B1;
    Z2 --> B2;
    Z2 --> Z3;
    Z2 --> C;
    Z2 --> E;
    Z2 --> F;
    Z2 --> G;

    Z3 --> Z5;
    Z3 --> B2;
    Z3 --> F;

    Z4 --> C;
    Z4 --> E;

    Z5 --> D;

    style A fill:#9cf,stroke:#333,stroke-width:2px
    style Z1 fill:#e0e0e0,stroke:#333,stroke-width:1px
    style Z2 fill:#e0e0e0,stroke:#333,stroke-width:1px
    style Z3 fill:#e0e0e0,stroke:#333,stroke-width:1px
    style Z4 fill:#e0e0e0,stroke:#333,stroke-width:1px
    style Z5 fill:#e0e0e0,stroke:#333,stroke-width:1px