# // crates/password_storage/Cargo.toml

[package]
name = "password_storage"
version = "0.1.0"
edition = "2021"

[dependencies]
password_core = { path = "../password_core" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
thiserror = "1.0"
anyhow = "1.0"
